### ISSUE TITLE
Legacy facility ID identifier is incorrect

### ISSUE THREAD

**Issue by fkleon** [HL7NZ/hpi#2]
It's currently defined as `https:////standards.digital.health.nz/ns/legacy-tbd-id` but should be `https://standards.digital.health.nz/ns/nzhis-facility-id`

**Comment by davidhay25** [comment]
fixed...

**Comment by davidhay25** [comment]
still fixed :)

**Comment by pkjordan** [comment]
Still incorrect, I think. 

The legacy Identifier for the HPI Facility ID is https://standards.digital.health.nz/id/hpi-facility as per http://igs.clinfhir.com/html/summary.html and production implementations (Healthpoint and Terminz).  That's certainly what was listed on https://standards.digital.health.nz/ until a couple of weeks ago.

A valid Naming System Resource that implements this can be found at... https://terminz.azurewebsites.net/fhir/NamingSystem/hpi-facility-id

**Comment by davidhay25** [comment]
We might be getting confused about 'legacy'. 

@fkleon - is this to correct the change that occurred in the url for the 'new' identifier from ..hpi-facility to ...hpi-facility-id, or is it intended to refer to a completely identifier that was used in the past?

**Comment by pkjordan** [comment]
There are 3 possibilities here...
a. Legacy URL identifier for the HPI Facility ID -  https://standards.digital.health.nz/id/hpi-facility
b. Legacy OID identifier for the HPI Facility ID - 2.16.840.1.113883.2.18.3.2
c. Legacy OID identifier for the HPI Facility CODE - 2.16.840.1.113883.2.18.76 (http://www.health.govt.nz/nz-health-statistics/data-references/code-tables/common-code-tables/facility-type-code-table) - I'm not sure if a URL identifier exists for this.

**Comment by fkleon** [comment]
Hi @pkjordan 

I'm not sure myself, will find out.

I believe a.  is the primary HPI facility ID of the format `FXXNNN-C`. As per https://standards.digital.health.nz/ the URL would be https://standards.digital.health.nz/ns/hpi-facility-id
